import { eq } from "drizzle-orm";
import { db } from "./index";
import {
  affiliates,
  agentRuns,
  applications,
  clients,
  countries,
  demands,
  deployments,
  emailsLog,
  employers,
  partners,
  payments,
  sequences,
  visaTypes,
  withdrawals,
} from "./schema";
import { COUNTRIES } from "@/lib/countries";
import { buildMrz, PACKAGES, PORTALS } from "@/lib/ops";

function daysAgo(days: number) {
  return new Date(Date.now() - days * 86400000);
}

function daysAhead(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export async function seedAll() {
  await db.insert(countries).values(
    COUNTRIES.map((country) => ({
      id: country.id,
      code: country.code,
      nameBn: country.nameBn,
      nameEn: country.nameEn,
      flag: country.flag,
      workPortal: country.portal,
      workBasis: country.workBasis,
      visitorCategory: country.visitor,
      selfPath: country.selfPath,
      processingDays: country.processing,
      highlight: country.highlight,
      accent: country.accent,
    })),
  );

  await db.insert(visaTypes).values([
    { id: 1, category: "Work", code: "WRK", nameBn: "ওয়ার্ক ভিসা", baseFee: 160000 },
    { id: 2, category: "Visitor", code: "VIS", nameBn: "ভিজিটর ভিসা", baseFee: 35000 },
    { id: 3, category: "Self_Sponsorship", code: "SLF", nameBn: "সেলফ-স্পন্সরশিপ", baseFee: 240000 },
  ]);

  const affiliateRows = await db
    .insert(affiliates)
    .values([
      {
        agentName: "কামাল হোসেন",
        district: "ঢাকা",
        upazila: "তেজগাঁও",
        phone: "+8801711002201",
        email: "kamal.dhaka@wvc-affiliate.example",
        referralCode: "WVC-DHK-01",
        walletBalance: 0,
        totalEarned: 10000,
        pendingWithdrawal: 10000,
      },
      {
        agentName: "রোকসানা বেগম",
        district: "চট্টগ্রাম",
        upazila: "চান্দগাঁও",
        phone: "+8801813004412",
        email: "roksana.ctg@wvc-affiliate.example",
        referralCode: "WVC-CTG-04",
        walletBalance: 0,
        totalEarned: 0,
        pendingWithdrawal: 0,
      },
      {
        agentName: "আনোয়ার হোসেন",
        district: "সিলেট",
        upazila: "সিলেট সদর",
        phone: "+8801914556670",
        email: "anwar.syl@wvc-affiliate.example",
        referralCode: "WVC-SYL-02",
        walletBalance: 3000,
        totalEarned: 3000,
        pendingWithdrawal: 0,
      },
      {
        agentName: "মিতু আক্তার",
        district: "রাজশাহী",
        upazila: "রাজশাহী সদর",
        phone: "+8801612883344",
        email: "mitu.raj@wvc-affiliate.example",
        referralCode: "WVC-RAJ-07",
        walletBalance: 15000,
        totalEarned: 15000,
        pendingWithdrawal: 0,
      },
    ])
    .returning();

  const aff = Object.fromEntries(affiliateRows.map((row) => [row.referralCode, row]));

  const employerRows = await db
    .insert(employers)
    .values([
      {
        companyName: "Balkan Forge DOO",
        countryCode: "SRB",
        tradeLicenseNo: "TL-SRB-44021",
        taxId: "TAX-SRB-109332",
        contactPerson: "Milan Petrović",
        contactTitle: "HR Director",
        email: "hr@balkanforge.example",
        phone: "+381111234401",
        website: "https://balkanforge.example",
        verificationStatus: "Verified",
        city: "Belgrade",
        sector: "Metal fabrication",
      },
      {
        companyName: "Ege Textile Sanayi A.Ş.",
        countryCode: "TUR",
        tradeLicenseNo: "TL-TUR-88211",
        taxId: "TAX-TUR-556701",
        contactPerson: "Ayşe Demir",
        contactTitle: "Plant Manager",
        email: "people@egetextile.example",
        phone: "+902321110045",
        website: "https://egetextile.example",
        verificationStatus: "Verified",
        city: "Izmir",
        sector: "Garments",
      },
      {
        companyName: "HarborCare Malta Ltd",
        countryCode: "MLT",
        tradeLicenseNo: "TL-MLT-19004",
        taxId: "VAT-MLT-2291",
        contactPerson: "Luca Borg",
        contactTitle: "Operations Lead",
        email: "jobs@harborcare.example",
        phone: "+35621003321",
        website: "https://harborcare.example",
        verificationStatus: "Verified",
        city: "Valletta",
        sector: "Hospitality",
      },
      {
        companyName: "Chisinau Pack Agro SRL",
        countryCode: "MDA",
        tradeLicenseNo: "TL-MDA-7712",
        taxId: "TAX-MDA-44190",
        contactPerson: "Ion Cebotari",
        contactTitle: "Owner",
        email: "ion@packagro.example",
        phone: "+37322100991",
        website: "https://packagro.example",
        verificationStatus: "Pending",
        city: "Chișinău",
        sector: "Agro packing",
      },
      {
        companyName: "Minsk Transit Logistics",
        countryCode: "BLR",
        tradeLicenseNo: "TL-BLR-3308",
        taxId: "TAX-BLR-88012",
        contactPerson: "Olga Ivanova",
        contactTitle: "Fleet Manager",
        email: "fleet@minsktransit.example",
        phone: "+375172200118",
        website: "https://minsktransit.example",
        verificationStatus: "Verified",
        city: "Minsk",
        sector: "Logistics",
      },
      {
        companyName: "Al Noor Contracting Co.",
        countryCode: "SAU",
        tradeLicenseNo: "CR-SAU-7015532",
        taxId: "TAX-SAU-300441",
        contactPerson: "Fahad Al-Harbi",
        contactTitle: "Recruitment Manager",
        email: "recruit@alnoorcontract.example",
        phone: "+966112008833",
        website: "https://alnoorcontract.example",
        verificationStatus: "Verified",
        city: "Riyadh",
        sector: "Construction",
      },
      {
        companyName: "Gulf Shadow Manpower",
        countryCode: "SAU",
        tradeLicenseNo: "CR-SAU-000991",
        taxId: "TAX-SAU-BLACK-19",
        contactPerson: "Unknown broker",
        contactTitle: "Agent",
        email: "desk@gulfshadow.example",
        phone: "+966500000019",
        website: "https://gulfshadow.example",
        verificationStatus: "Blacklisted",
        city: "Jeddah",
        sector: "Manpower",
        blacklistReason: "পূর্বে মজুরি বকেয়া, ভুয়া ডিমান্ড লেটার এবং শ্রমিককে অন্য সাইটে স্থানান্তরের অভিযোগ।",
      },
      {
        companyName: "Pearl Facilities W.L.L.",
        countryCode: "BHR",
        tradeLicenseNo: "CR-BHR-55210",
        taxId: "TAX-BHR-22018",
        contactPerson: "Hana Yusuf",
        contactTitle: "CR Administrator",
        email: "hr@pearlfacilities.example",
        phone: "+97317001122",
        website: "https://pearlfacilities.example",
        verificationStatus: "Verified",
        city: "Manama",
        sector: "Facilities",
      },
      {
        companyName: "Senai Precision Sdn Bhd",
        countryCode: "MYS",
        tradeLicenseNo: "SSM-MYS-202118",
        taxId: "TAX-MYS-88120",
        contactPerson: "Daniel Tan",
        contactTitle: "Plant HR",
        email: "hr@senaiprecision.example",
        phone: "+6073312008",
        website: "https://senaiprecision.example",
        verificationStatus: "Verified",
        city: "Johor",
        sector: "Precision engineering",
      },
      {
        companyName: "Anatolia Cloud Kitchen",
        countryCode: "TUR",
        tradeLicenseNo: "TL-TUR-12009",
        taxId: "TAX-TUR-PEND-2",
        contactPerson: "Emre Kaya",
        contactTitle: "Founder",
        email: "emre@anatoliakitchen.example",
        phone: "+902122200091",
        website: "https://anatoliakitchen.example",
        verificationStatus: "Pending",
        city: "Istanbul",
        sector: "Hospitality",
      },
    ])
    .returning();

  const emp = Object.fromEntries(employerRows.map((row) => [row.taxId, row]));

  const demandRows = await db
    .insert(demands)
    .values([
      {
        employerId: emp["TAX-SRB-109332"].id,
        jobTitle: "Welder",
        jobTitleBn: "ওয়েল্ডার",
        requiredWorkers: 18,
        fulfilledCount: 4,
        salary: 750,
        currency: "EUR",
        hoursPerDay: 8,
        overtimePolicy: "ঘণ্টাপ্রতি ১.২৫ গুণ, মাসে সর্বোচ্চ ৩০ ঘণ্টা",
        housing: "শেয়ার্ড",
        medical: "বেসিক ইনশিওরেন্স",
        foodAllowance: "আংশিক",
        status: "Open",
        demandLetterRef: "DL-SRB-2026-014",
      },
      {
        employerId: emp["TAX-TUR-556701"].id,
        jobTitle: "Sewing operator",
        jobTitleBn: "সেলাই অপারেটর",
        requiredWorkers: 40,
        fulfilledCount: 11,
        salary: 28000,
        currency: "TRY",
        hoursPerDay: 9,
        overtimePolicy: "সাপ্তাহিক ৪৫ ঘণ্টার পর ওভারটাইম",
        housing: "ডরমিটরি",
        medical: "SGK",
        foodAllowance: "একবেলা",
        status: "Open",
        demandLetterRef: "DL-TUR-2026-088",
      },
      {
        employerId: emp["VAT-MLT-2291"].id,
        jobTitle: "Housekeeping attendant",
        jobTitleBn: "হাউসকিপিং",
        requiredWorkers: 8,
        fulfilledCount: 1,
        salary: 980,
        currency: "EUR",
        hoursPerDay: 8,
        overtimePolicy: "রোস্টার অনুযায়ী",
        housing: "স্টাফ অ্যাকোমোডেশন",
        medical: "স্থানীয় বীমা",
        foodAllowance: "শিফট মিল",
        status: "Open",
        demandLetterRef: "DL-MLT-2026-006",
      },
      {
        employerId: emp["TAX-MDA-44190"].id,
        jobTitle: "Packing line worker",
        jobTitleBn: "প্যাকিং লাইন",
        requiredWorkers: 12,
        fulfilledCount: 0,
        salary: 700,
        currency: "EUR",
        hoursPerDay: 8,
        overtimePolicy: "মৌসুমে অতিরিক্ত শিফট",
        housing: "শেয়ার্ড",
        medical: "বেসিক",
        foodAllowance: "না",
        status: "Paused",
        demandLetterRef: "DL-MDA-2026-003",
      },
      {
        employerId: emp["TAX-BLR-88012"].id,
        jobTitle: "Light truck driver",
        jobTitleBn: "হালকা ট্রাক ড্রাইভার",
        requiredWorkers: 6,
        fulfilledCount: 1,
        salary: 900,
        currency: "USD",
        hoursPerDay: 8,
        overtimePolicy: "ট্রিপ ভিত্তিক",
        housing: "কোম্পানি ফ্ল্যাট",
        medical: "কোম্পানি কভার",
        foodAllowance: "দৈনিক ভাতা",
        status: "Open",
        demandLetterRef: "DL-BLR-2026-011",
      },
      {
        employerId: emp["TAX-SAU-300441"].id,
        jobTitle: "General construction worker",
        jobTitleBn: "নির্মাণ শ্রমিক",
        requiredWorkers: 80,
        fulfilledCount: 22,
        salary: 1400,
        currency: "SAR",
        hoursPerDay: 8,
        overtimePolicy: "কিওয়া চুক্তি অনুযায়ী",
        housing: "ক্যাম্প",
        medical: "ওয়াফিদ ফিট + সাইট কভার",
        foodAllowance: "তিন বেলা",
        status: "Open",
        demandLetterRef: "DL-SAU-2026-220",
      },
      {
        employerId: emp["TAX-SAU-BLACK-19"].id,
        jobTitle: "Cleaner",
        jobTitleBn: "ক্লিনার",
        requiredWorkers: 30,
        fulfilledCount: 0,
        salary: 900,
        currency: "SAR",
        hoursPerDay: 10,
        overtimePolicy: "অস্পষ্ট",
        housing: "অনুল্লেখিত",
        medical: "নেই",
        foodAllowance: "নেই",
        status: "Closed",
        demandLetterRef: "DL-FAKE-019",
      },
      {
        employerId: emp["TAX-BHR-22018"].id,
        jobTitle: "Facilities technician",
        jobTitleBn: "ফ্যাসিলিটিজ টেকনিশিয়ান",
        requiredWorkers: 10,
        fulfilledCount: 2,
        salary: 220,
        currency: "BHD",
        hoursPerDay: 8,
        overtimePolicy: "এলএমআরএ চুক্তি অনুযায়ী",
        housing: "শেয়ার্ড ফ্ল্যাট",
        medical: "SIO ক্লিয়ারেন্স",
        foodAllowance: "ভাতা",
        status: "Open",
        demandLetterRef: "DL-BHR-2026-017",
      },
      {
        employerId: emp["TAX-MYS-88120"].id,
        jobTitle: "CNC technician",
        jobTitleBn: "সিএনসি টেকনিশিয়ান",
        requiredWorkers: 9,
        fulfilledCount: 2,
        salary: 2200,
        currency: "MYR",
        hoursPerDay: 8,
        overtimePolicy: "১.৫ গুণ",
        housing: "হোস্টেল",
        medical: "SOCSO নোট",
        foodAllowance: "ক্যান্টিন",
        status: "Open",
        demandLetterRef: "DL-MYS-2026-042",
      },
    ])
    .returning();

  const demandByRef = Object.fromEntries(demandRows.map((row) => [row.demandLetterRef, row]));

  const clientSeed = [
    {
      code: "WVC-SRB-WRK-2026-0001",
      name: "মো. রাহিম উদ্দিন",
      passport: "A04551219",
      phone: "+8801711223344",
      email: "rahim.uddin@client.example",
      age: 29,
      skill: "MIG ওয়েল্ডার",
      country: "SRB",
      visa: "WRK" as const,
      status: "deployed",
      aff: "WVC-DHK-01",
      demand: "DL-SRB-2026-014",
      entered: 2,
      created: 48,
      paid: [
        { stage: "Advance", amount: 66000, method: "bKash", trx: "BKH8R21Q" },
        { stage: "Stage_2", amount: 88000, method: "Bank", trx: "DBBL44021" },
        { stage: "Final", amount: 66000, method: "Nagad", trx: "NGD77120" },
      ],
      police: daysAhead(-20),
      bank: 180000,
      photo: 146,
      tracking: "PPZ-104488",
      portalStatus: "Unified card issued",
    },
    {
      code: "WVC-SAU-WRK-2026-0002",
      name: "মো. করিম মিয়া",
      passport: "A07880021",
      phone: "+8801811556677",
      email: "karim.mia@client.example",
      age: 34,
      skill: "নির্মাণ শ্রমিক",
      country: "SAU",
      visa: "WRK" as const,
      status: "permit_submitted",
      aff: "WVC-CTG-04",
      demand: "DL-SAU-2026-220",
      entered: 3,
      created: 21,
      paid: [
        { stage: "Advance", amount: 48000, method: "bKash", trx: "BKH22018" },
        { stage: "Stage_2", amount: 64000, method: "Nagad", trx: "NGD90811" },
      ],
      police: daysAhead(-12),
      bank: 90000,
      photo: 132,
      tracking: "QIWA-44019283",
      portalStatus: "Qiwa contract generated, Enjaz pending",
    },
    {
      code: "WVC-TUR-WRK-2026-0003",
      name: "নুসরাত জাহান",
      passport: "A06221190",
      phone: "+8801912003344",
      email: "nusrat.jahan@client.example",
      age: 26,
      skill: "সেলাই অপারেটর",
      country: "TUR",
      visa: "WRK" as const,
      status: "embassy_review",
      aff: null,
      demand: "DL-TUR-2026-088",
      entered: 4,
      created: 36,
      paid: [
        { stage: "Advance", amount: 84000, method: "Bank", trx: "EBL19002" },
        { stage: "Stage_2", amount: 112000, method: "bKash", trx: "BKH55190" },
      ],
      police: daysAhead(-30),
      bank: 120000,
      photo: 151,
      tracking: "4482910033447781",
      portalStatus: "16-digit reference matched with e-İzin file",
    },
    {
      code: "WVC-MLT-VIS-2026-0004",
      name: "ফারহানা আক্তার",
      passport: "EA1988334",
      phone: "+8801612445566",
      email: "farhana.akter@client.example",
      age: 31,
      skill: "পর্যটন — পারিবারিক সফর",
      country: "MLT",
      visa: "VIS" as const,
      status: "docs_verified",
      aff: "WVC-SYL-02",
      demand: null,
      entered: 1,
      created: 6,
      paid: [{ stage: "Advance", amount: 20000, method: "Nagad", trx: "NGD30021" }],
      police: daysAhead(-8),
      bank: 240000,
      photo: 128,
      tracking: null,
      portalStatus: "Schengen pack assembled",
    },
    {
      code: "WVC-BHR-WRK-2026-0005",
      name: "জাহিদুল ইসলাম",
      passport: "A03334421",
      phone: "+8801719002288",
      email: "jahidul.islam@client.example",
      age: 32,
      skill: "ইলেকট্রিশিয়ান",
      country: "BHR",
      visa: "WRK" as const,
      status: "employer_selected",
      aff: "WVC-RAJ-07",
      demand: "DL-BHR-2026-017",
      entered: 9,
      created: 18,
      paid: [{ stage: "Advance", amount: 51000, method: "bKash", trx: "BKH77165" }],
      police: daysAhead(-15),
      bank: 80000,
      photo: 119,
      tracking: null,
      portalStatus: "LMRA 7-day vacancy window running",
    },
    {
      code: "WVC-MYS-SLF-2026-0006",
      name: "তানভীর হাসান",
      passport: "A09001277",
      phone: "+8801555667788",
      email: "tanvir.hasan@client.example",
      age: 36,
      skill: "সফটওয়্যার ডিরেক্টর",
      country: "MYS",
      visa: "SLF" as const,
      status: "new_lead",
      aff: null,
      demand: null,
      entered: 0,
      created: 1,
      paid: [] as { stage: string; amount: number; method: string; trx: string }[],
      police: daysAhead(-5),
      bank: 1800000,
      photo: 160,
      tracking: null,
      portalStatus: "Sdn Bhd checklist opened",
    },
    {
      code: "WVC-MDA-WRK-2026-0007",
      name: "সুমাইয়া খাতুন",
      passport: "A02119930",
      phone: "+8801812667781",
      email: "sumaiya.khatun@client.example",
      age: 27,
      skill: "প্যাকিং সুপারভাইজার",
      country: "MDA",
      visa: "WRK" as const,
      status: "permit_submitted",
      aff: "WVC-DHK-01",
      demand: "DL-MDA-2026-003",
      entered: 11,
      created: 27,
      paid: [{ stage: "Advance", amount: 54000, method: "Bank", trx: "IBBL8801" }],
      police: daysAhead(-40),
      bank: 70000,
      photo: 109,
      tracking: "IGM-2291844",
      portalStatus: "ANOFM opinion overdue",
    },
    {
      code: "WVC-BLR-VIS-2026-0008",
      name: "রফিক আহমেদ",
      passport: "A05550912",
      phone: "+8801912776655",
      email: "rafiq.ahmed@client.example",
      age: 41,
      skill: "ব্যবসায়িক সফর",
      country: "BLR",
      visa: "VIS" as const,
      status: "embassy_review",
      aff: "WVC-CTG-04",
      demand: null,
      entered: 2,
      created: 14,
      paid: [
        { stage: "Advance", amount: 12000, method: "Nagad", trx: "NGD44190" },
        { stage: "Stage_2", amount: 15000, method: "bKash", trx: "BKH22910" },
      ],
      police: daysAhead(-9),
      bank: 210000,
      photo: 121,
      tracking: "CMD-7712033",
      portalStatus: "Tourist voucher received at consulate",
    },
    {
      code: "WVC-SAU-VIS-2026-0009",
      name: "আয়েশা সিদ্দিকা",
      passport: "EA2210091",
      phone: "+8801612009988",
      email: "ayesha.siddika@client.example",
      age: 38,
      skill: "পারিবারিক ভিজিট",
      country: "SAU",
      visa: "VIS" as const,
      status: "visa_approved",
      aff: "WVC-SYL-02",
      demand: null,
      entered: 1,
      created: 16,
      paid: [
        { stage: "Advance", amount: 20000, method: "bKash", trx: "BKH30091" },
        { stage: "Final", amount: 35000, method: "Nagad", trx: "NGD30092" },
      ],
      police: daysAhead(-6),
      bank: 260000,
      photo: 138,
      tracking: "NUSUK-882110",
      portalStatus: "Visit visa granted",
    },
    {
      code: "WVC-TUR-SLF-2026-0010",
      name: "ইমরান হোসেন",
      passport: "A08881230",
      phone: "+8801712550099",
      email: "imran.hossain@client.example",
      age: 33,
      skill: "খাদ্য উদ্যোক্তা",
      country: "TUR",
      visa: "SLF" as const,
      status: "docs_verified",
      aff: null,
      demand: null,
      entered: 5,
      created: 9,
      paid: [{ stage: "Advance", amount: 126000, method: "Bank", trx: "DBBL22019" }],
      police: daysAhead(-18),
      bank: 2400000,
      photo: 144,
      tracking: null,
      portalStatus: "Tax ID appointment queued",
    },
    {
      code: "WVC-SRB-SLF-2026-0011",
      name: "মাহমুদুল হাসান",
      passport: "A01227761",
      phone: "+8801812990011",
      email: "mahmudul.hasan@client.example",
      age: 40,
      skill: "ট্রেডিং কোম্পানি ডিরেক্টর",
      country: "SRB",
      visa: "SLF" as const,
      status: "deployed",
      aff: "WVC-RAJ-07",
      demand: null,
      entered: 6,
      created: 55,
      paid: [
        { stage: "Advance", amount: 78000, method: "Bank", trx: "SONALI771" },
        { stage: "Stage_2", amount: 104000, method: "bKash", trx: "BKH10400" },
        { stage: "Final", amount: 78000, method: "Bank", trx: "SONALI772" },
      ],
      police: daysAhead(-25),
      bank: 900000,
      photo: 133,
      tracking: "PPZ-220198",
      portalStatus: "DOO registered, director permit issued",
    },
    {
      code: "WVC-MYS-WRK-2026-0012",
      name: "শাবনম পারভীন",
      passport: "A06660018",
      phone: "+8801912447788",
      email: "shabnam.parvin@client.example",
      age: 28,
      skill: "সিএনসি অপারেটর",
      country: "MYS",
      visa: "WRK" as const,
      status: "rejected",
      aff: "WVC-DHK-01",
      demand: "DL-MYS-2026-042",
      entered: 3,
      created: 24,
      paid: [{ stage: "Advance", amount: 63000, method: "Nagad", trx: "NGD66018" }],
      police: daysAhead(-11),
      bank: 65000,
      photo: 102,
      tracking: "ESD-19002811",
      portalStatus: "Calling visa refused — skill evidence insufficient",
    },
  ];

  for (const item of clientSeed) {
    const contract = PACKAGES[item.country][item.visa];
    const expiry = daysAhead(420);
    const [client] = await db
      .insert(clients)
      .values({
        clientCode: item.code,
        fullName: item.name,
        passportNo: item.passport,
        passportExpiry: expiry,
        phone: item.phone,
        email: item.email,
        age: item.age,
        skill: item.skill,
        countryCode: item.country,
        visaCode: item.visa,
        status: item.status,
        affiliateId: item.aff ? aff[item.aff].id : null,
        demandId: item.demand ? demandByRef[item.demand].id : null,
        contractValue: contract,
        photoScore: item.photo,
        policeClearanceDate: item.police,
        bankBalance: item.bank,
        mrzLine: buildMrz(item.passport, expiry, item.name),
        validationNotes: "সিড ডসিয়ার — পাসপোর্ট মেয়াদ, ছবি ও ক্লিয়ারেন্স উত্তীর্ণ।",
        commissionCredited: item.status === "visa_approved" || item.status === "deployed",
        rejectionReason:
          item.status === "rejected"
            ? "দূতাবাস: দক্ষতার প্রমাণ ও অভিজ্ঞতার সনদ অপর্যাপ্ত। আপিলের জন্য নতুন স্কিল টেস্ট সনদ লাগবে।"
            : null,
        createdAt: daysAgo(item.created),
        updatedAt: daysAgo(item.entered),
        stageEnteredAt: daysAgo(item.entered),
      })
      .returning();

    await db.insert(applications).values({
      clientId: client.id,
      stage: item.status === "rejected" ? "embassy_review" : item.status,
      permitSubmissionDate: ["permit_submitted", "embassy_review", "visa_approved", "deployed", "rejected"].includes(item.status)
        ? daysAgo(item.created - 8)
        : null,
      embassyDate: ["embassy_review", "visa_approved", "deployed", "rejected"].includes(item.status)
        ? daysAgo(Math.max(item.entered, 1))
        : null,
      govTrackingCode: item.tracking,
      portal: PORTALS[item.country],
      portalStatus: item.portalStatus,
      notes: item.status === "rejected" ? "Refusal recorded. Appeal window open." : "Pipeline synced from operations seed.",
    });

    for (const payment of item.paid) {
      await db.insert(payments).values({
        clientId: client.id,
        amount: payment.amount,
        paymentMethod: payment.method,
        paymentStage: payment.stage,
        invoiceNo: `INV-2026-${item.code.slice(-4)}${payment.stage.slice(0, 1)}`,
        trxId: payment.trx,
        createdAt: daysAgo(item.created - 1),
      });
    }

    await db.insert(emailsLog).values({
      clientId: client.id,
      recipientEmail: item.email,
      subject: `আপনার ফাইল সফলভাবে জমা হয়েছে - আইডি: ${item.code}`,
      triggerType: "onboarding",
      bodyPreview: `প্রিয় ${item.name}, আপনার ট্র্যাকিং রেফারেন্স ${item.code}। অফিস: info@worldvisionconsultancy.com`,
      timestamp: daysAgo(item.created),
    });

    if (item.status === "visa_approved" || item.status === "deployed") {
      const affiliate = item.aff ? aff[item.aff] : null;
      if (affiliate) {
        const commission = item.visa === "WRK" ? 10000 : item.visa === "VIS" ? 3000 : 15000;
        await db.insert(emailsLog).values({
          clientId: client.id,
          recipientEmail: affiliate.email,
          subject: `আপনার রেফার করা ক্লায়েন্ট ${item.name} এর ফাইল Approved হয়েছে - কমিশন ${commission.toLocaleString("bn-BD")} টাকা যোগ হয়েছে`,
          triggerType: "affiliate_commission",
          bodyPreview: `রেফারেল ${affiliate.referralCode} এর লেজারে কমিশন ক্রেডিট হয়েছে।`,
          timestamp: daysAgo(item.entered + 1),
        });
      }
    }

    if (item.status === "deployed") {
      await db.insert(deployments).values({
        clientId: client.id,
        flightDate: daysAgo(-12),
        airline: item.country === "SRB" ? "Air Serbia" : "Biman Bangladesh",
        pnrNumber: item.country === "SRB" ? "SRB7KQ" : "BG44LM",
        airportPickupStatus: item.code.endsWith("0001"),
        briefing: "গন্তব্য নিয়োগকর্তার পিকআপ ডেস্ক ও জরুরি হটলাইন ডসিয়ারে সংযুক্ত।",
      });
      await db.insert(emailsLog).values({
        clientId: client.id,
        recipientEmail: item.email,
        subject: `চূড়ান্ত ফ্লাইট ব্রিফিং — ${item.code}`,
        triggerType: "flight_briefing",
        bodyPreview: "টিকিট, নিয়োগকর্তার ঠিকানা ও জরুরি সহায়তা নির্দেশিকা সংযুক্ত।",
        timestamp: daysAgo(1),
      });
    }
  }

  await db.insert(partners).values([
    {
      employerId: emp["TAX-SRB-109332"].id,
      commissionRate: 12,
      agreementRef: "AGR-SRB-014",
      profitShareBalance: 186000,
      recruitingFee: 45000,
      liabilityNote: "মেডিকেল ফেল হলে রিক্রুটিং ফি আংশিক ফেরত।",
    },
    {
      employerId: emp["TAX-SAU-300441"].id,
      commissionRate: 10,
      agreementRef: "AGR-SAU-220",
      profitShareBalance: 640000,
      recruitingFee: 28000,
      liabilityNote: "ওয়াফিদ আনফিট হলে প্রতিস্থাপন ৩০ দিনের মধ্যে।",
    },
    {
      employerId: emp["TAX-BHR-22018"].id,
      commissionRate: 11,
      agreementRef: "AGR-BHR-017",
      profitShareBalance: 92000,
      recruitingFee: 32000,
      liabilityNote: "এলএমআরএ রিজেক্ট হলে সার্ভিস চার্জের ৫০% সমন্বয়।",
    },
    {
      employerId: emp["TAX-MYS-88120"].id,
      commissionRate: 9,
      agreementRef: "AGR-MYS-042",
      profitShareBalance: 74000,
      recruitingFee: 36000,
      liabilityNote: "ESD কোটা শেষ হলে ডিমান্ড পজ করা হবে।",
    },
  ]);

  await db.insert(withdrawals).values({
    affiliateId: aff["WVC-DHK-01"].id,
    amount: 10000,
    method: "bKash",
    account: "01711002201",
    status: "Pending",
    createdAt: daysAgo(1),
  });

  const shifts = ["09:00", "14:00", "21:00"];
  for (const country of COUNTRIES) {
    await db.insert(agentRuns).values({
      countryCode: country.code,
      portal: country.portal,
      runType: "slot_scan",
      shift: shifts[country.id % 3],
      result: `${country.nameBn} পোর্টাল সেশন সিমুলেশন সম্পন্ন। বাহ্যিক সাইটে কোনো অনুরোধ পাঠানো হয়নি।`,
      slotsFound: country.code === "SRB" || country.code === "SAU" ? 2 : country.id % 2,
      createdAt: daysAgo(country.id % 3),
    });
  }

  await db.insert(sequences).values({ year: new Date().getFullYear(), lastValue: 12 });
}
